#!/bin/bash
#SBATCH -t 00:30:00
#SBATCH --ntasks-per-node=16
#SBATCH -c 8
#SBATCH -N 1
#SBATCH -J "H2"
#SBATCH --account=hpc-prf-metdyn
##SBATCH -p largemem
#SBATCH -q express

export OMP_NUM_THREADS=8
export OMP_PLACES=cores
export OMP_PROC_BIND=true

module purge
module load chem/CP2K/2024.1-foss-2023b-gcc-openmpi-openblas-libgrpp

rm cp2k.out
srun /pc2/groups/hpc-prf-metdyn/metdyn02_Remi/cp2k/vanilla/cp2k/exe/local/cp2k.pdbg *inp >> cp2k.out
